---
title: "Line distribution on cinema"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  html_notebook:
    toc: yes
    toc_float: yes
---


```{r setup, echo=FALSE, warning=FALSE, message=FALSE}

library(here)
library(cluster)
library(tidyverse)
library(broom)
library(mclust)
library(NbClust)

theme_set(theme_bw())
```

# Data Overview

```{r, warning=FALSE}
read_csv(here("data/character_list5.csv"),
                      progress = FALSE,
                      col_types = cols(
                                    script_id = col_integer(),
                                    imdb_character_name = col_character(),
                                    words = col_integer(),
                                    gender = col_character(),
                                    age = col_character()
                                    )) %>%
  mutate(age = as.numeric(age)) -> characters_list

characters_list %>% 
  glimpse()

```

```{r}
read_csv(here("data/meta_data7.csv"),
                      progress = FALSE,
         col_types = cols(
                        script_id = col_integer(),
                        imdb_id = col_character(),
                        title = col_character(),
                        year = col_integer(),
                        gross = col_integer(),
                        lines_data = col_character()
                        )) -> meta_data

meta_data %>% 
  glimpse()

```

## Combinando Dados Originais

```{r}
left_join(characters_list, 
          meta_data, 
          by=c("script_id")) %>%
  group_by(title, year) %>%
  drop_na(gross) %>%
  ungroup() -> scripts_data

scripts_data %>%
  glimpse()
```

## Words

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  ggplot(aes(x=words,
             y=(..count..)/sum(..count..))) +
  geom_histogram(binwidth = 250,
                 boundary = 0,
                 fill = "grey",
                 color = "black")
```

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  ggplot(aes(x="", 
             y=words)) +
  geom_violin(fill="grey",
               width=0.5)
```


## Female Proportion 

```{r}
scripts_data %>%
  group_by(title, year) %>%
  mutate(fem_prop = (sum(gender == "f") / n()),
         man_prop = (1 - fem_prop)) %>% 
  ungroup() -> scripts_data

scripts_data %>%
  select(title,
         year,
         fem_prop,
         man_prop) %>%
  sample_n(10)
```


```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  ggplot(aes(x=fem_prop,
             y=(..count..)/sum(..count..))) +
  geom_histogram(binwidth = 0.05,
                 boundary = 0,
                 fill = "grey",
                 color = "black")
```

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  ggplot(aes(x="", 
             y=fem_prop)) +
  geom_violin(fill="grey",
               width=0.5)
```

## Movie Year 

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  ggplot(aes(x=year)) +
  geom_bar(fill = "grey",
           color = "black")
```

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  ggplot(aes(x="", 
             y=year)) +
  geom_violin(fill="grey",
               width=0.5)
```

```{r}
scripts_data %>%
  mutate(fem_words = ifelse(gender == "f",words,0),
         man_words = ifelse(gender == "m",words,0)) %>%
  group_by(title, year) %>%
  mutate(mean_fem_words = ifelse(sum(gender == "f") == 0, 0, sum(fem_words)/sum(gender == "f")),
         mean_man_words = ifelse(sum(gender == "m") == 0, 0, sum(man_words)/sum(gender == "m"))) %>% 
  ungroup()  -> scripts_data

scripts_data %>%
  select(title,
         year,
         mean_fem_words,
         mean_man_words) %>%
  sample_n(10)
```

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  filter(!mean_fem_words == 0) %>%
  ggplot(aes(x=mean_fem_words,
             y=(..count..)/sum(..count..))) +
  geom_histogram(binwidth = 250,
                 boundary = 0,
                 fill = "grey",
                 color = "black")
```

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  filter(!mean_fem_words == 0) %>%
  ggplot(aes(x="", 
             y=mean_fem_words)) +
  geom_violin(fill="grey",
               width=0.5)
```

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  filter(!mean_man_words == 0) %>%
  ggplot(aes(x=mean_man_words,
             y=(..count..)/sum(..count..))) +
  geom_histogram(binwidth = 250,
                 boundary = 0,
                 fill = "grey",
                 color = "black")
```

```{r}
scripts_data %>%
  group_by(title,year) %>%
  unique() %>%
  filter(!mean_man_words == 0) %>%
  ggplot(aes(x="", 
             y=mean_man_words)) +
  geom_violin(fill="grey",
               width=0.5)
```

### Scale Data

```{r}
scripts_data %>%
  group_by(title) %>%
  slice(1) %>%
  unique() %>%
  ungroup() %>%
  select(title,
         gross,
         fem_prop,
         mean_fem_words,
         mean_man_words) -> data

select(data, -title) %>%
mutate_all(funs(scale)) -> scaled_data

scaled_data %>% 
  sample_n(10)
```

## Número K ótimo 

### GAP statistic

A GAP compara a solução do agrupamento com cada k com a solução em um dataset onde não há estrutura de grupos. 

```{r}
plot_clusgap = function(clusgap, title="Gap Statistic calculation results"){
    require("ggplot2")
    gstab = data.frame(clusgap$Tab, k=1:nrow(clusgap$Tab))
    p = ggplot(gstab, aes(k, gap)) + geom_line() + geom_point(size=5)
    p = p + geom_errorbar(aes(ymax=gap+SE.sim, ymin=gap-SE.sim), width = .2)
    p = p + ggtitle(title)
    return(p)
}
```

```{r}
gaps <- scaled_data %>% 
    clusGap(FUN = kmeans,
            nstart = 20,
            K.max = 8,
            B = 200,
            iter.max=30)
```

```{r}
plot_clusgap(gaps)
```

```{r}
row.names(scaled_data)  = data$title
dists = dist(scaled_data, method = "euclidean")
hc = hclust(dists, method = "ward.D")
hcd <- as.dendrogram(hc)
# plot(hc)

nodePar <- list(lab.cex = 0.1, pch = c(NA, 19), 
                cex = 0.1, col = "white")
# Customized plot; remove labels
plot(hcd,
     ylab = "Height", 
     nodePar = nodePar,
     leaflab = "none",
     horiz = TRUE)
```

```{r}
set.seed(123)
# Compute and plot wss for k = 2 to k = 15.
k.max <- 15

wss <- sapply(1:k.max, 
              function(k){kmeans(scaled_data, k, nstart=50,iter.max = 15 )$tot.withinss})
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")
```

* Pelo Elbow method 4 parece ser um bom número de grupos.

```{r}
library (vegan)
library (cluster)

data(varespec)
dis = dist(scaled_data)^2
res = kmeans(scaled_data,3)
sil = silhouette (res$cluster, dis)
plot(sil)
```


```{r}
d_clust <- Mclust(as.matrix(scaled_data), G=1:15, 
                  modelNames = mclust.options("emModelNames"))
d_clust$BIC
```

```{r}
plot(d_clust$BIC)
```

```{r}
nb <- NbClust(scaled_data, diss=NULL, distance = "euclidean", 
              min.nc=2, max.nc=5, method = "kmeans", 
              index = "all", alphaBeale = 0.1)
hist(nb$Best.nc[1,], breaks = max(na.omit(nb$Best.nc[1,])))
```


```{r}
# toclust = x %>% 
#     rownames_to_column(var = "language") %>% 
#     select(1:5) 
# dists = toclust %>% 
#     select(-language) %>% 
#     dist() # só para plotar silhouetas depois
# km = toclust %>% 
#     select(-language) %>% 
#     kmeans(centers = n_clusters, nstart = 20)
# km %>% 
#     augment(toclust) %>% 
#     gather(key = "variável", value = "valor", -language, -.cluster) %>% 
#     ggplot(aes(x = `variável`, y = valor, group = language, colour = .cluster)) + 
#     geom_point(alpha = 0.2) + 
#     geom_line(alpha = .5) + 
#     facet_wrap(~ .cluster) 
```

```{r}
library(GGally)
data(crabs, package = "MASS")
ggparcoord(crabs, columns = 4:8, groupColumn = "sp")
```

```{r}
library(GGally)
x <- rnorm(100)
d1 <- data.frame(x1 = x, x2 = rnorm(x), x3 = x)
d2 <- mutate(d1, x3 = -x)
ggparcoord(d1)
library(lattice)
parallelplot(d1)
```

